In [51]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier

In [52]:
iris = load_iris()

In [53]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [54]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.20, random_state=42)

In [55]:
X_train.shape

(120, 4)

In [56]:
X_test.shape

(30, 4)

In [57]:
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

1.0

In [58]:
svc = SVC()
svc.fit(X_train, y_train)
svc.score(X_test, y_test)

1.0

In [59]:
rf =RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

1.0

In [60]:
def get_score(model, X_train, y_train, X_test, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [61]:
get_score(lr, X_train, y_train, X_test, y_test)

1.0

In [62]:
get_score(svc, X_train, y_train, X_test, y_test)

1.0

In [63]:
get_score(rf, X_train, y_train, X_test, y_test)

1.0

In [64]:
from sklearn.model_selection import KFold

In [65]:
fold = KFold()

In [66]:
l = [1, 2, 3, 4, 5, 6, 7, 8, 9]

In [67]:
fold = KFold(n_splits=3)

In [68]:
fold.split(l)

<generator object _BaseKFold.split at 0x0000016832CB2680>

In [69]:
for train_index, test_index in fold.split(l):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [70]:
from sklearn.model_selection import StratifiedKFold

In [71]:
kf = StratifiedKFold(n_splits=3)

In [72]:
l = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
l1 = [0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]

In [73]:
for train_index, test_index in kf.split(l, l1):
    print(train_index, test_index)

[ 2  3  5  6  7  9 10 11] [0 1 4 8]
[ 0  1  3  4  7  8 10 11] [2 5 6 9]
[0 1 2 4 5 6 8 9] [ 3  7 10 11]


In [74]:
lr_score = []
svc_score = []
rf_score = []

In [75]:
iris.data[2]

array([4.7, 3.2, 1.3, 0.2])

In [76]:
lr_score = []
svc_score = []
rf_score = []
for train_index, test_index in kf.split(iris.data, iris.target):
    X_train, X_test = iris.data[train_index], iris.data[test_index]
    y_train, y_test = iris.target[train_index],iris.target[test_index]
    lr_score.append(get_score(lr, X_train, y_train, X_test, y_test))
    svc_score.append(get_score(svc, X_train, y_train, X_test, y_test))
    rf_score.append(get_score(rf, X_train, y_train, X_test, y_test))

In [77]:
X_train.shape

(100, 4)

In [78]:
X_test.shape

(50, 4)

In [79]:
lr_score

[0.98, 0.96, 0.98]

In [80]:
svc_score

[0.96, 0.98, 0.94]

In [81]:
rf_score

[0.98, 0.94, 0.98]

In [82]:
np.mean(lr_score)

0.9733333333333333

In [83]:
np.mean(svc_score)

0.96

In [84]:
np.mean(rf_score)

0.9666666666666667

In [85]:
from sklearn.model_selection import cross_val_score

In [86]:
cross_val_score(LogisticRegression(max_iter=7600), iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [87]:
cross_val_score(SVC(kernel='poly'), iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [88]:
cross_val_score(RandomForestClassifier(), iris.data, iris.target, cv=5)

array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])