In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [4]:
df = pd.read_csv("data.csv")

In [5]:
df.head()

Car       Model  Volume  Weight  CO2
0      Toyoty        Aygo    1000     790   99
1  Mitsubishi  Space Star    1200    1160   95
2       Skoda      Citigo    1000     929   95
3        Fiat         500     900     865   90
4        Mini      Cooper    1500    1140  105

In [6]:
df.shape

(36, 5)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Car     36 non-null     object
 1   Model   36 non-null     object
 2   Volume  36 non-null     int64 
 3   Weight  36 non-null     int64 
 4   CO2     36 non-null     int64 
dtypes: int64(3), object(2)
memory usage: 1.5+ KB


In [9]:
df.isnull().sum()

Car       0
Model     0
Volume    0
Weight    0
CO2       0
dtype: int64

In [10]:
df.describe()

Volume       Weight         CO2
count    36.000000    36.000000   36.000000
mean   1611.111111  1292.277778  102.027778
std     388.975047   242.123889    7.454571
min     900.000000   790.000000   90.000000
25%    1475.000000  1117.250000   97.750000
50%    1600.000000  1329.000000   99.000000
75%    2000.000000  1418.250000  105.000000
max    2500.000000  1746.000000  120.000000

In [11]:
x = df[['Volume', 'Weight']]
x

Volume  Weight
0     1000     790
1     1200    1160
2     1000     929
3      900     865
4     1500    1140
5     1000     929
6     1400    1109
7     1500    1365
8     1500    1112
9     1600    1150
10    1100     980
11    1300     990
12    1000    1112
13    1600    1252
14    1600    1326
15    1600    1330
16    1600    1365
17    2200    1280
18    1600    1119
19    2000    1328
20    1600    1584
21    2000    1428
22    2100    1365
23    1600    1415
24    2000    1415
25    1500    1465
26    2000    1490
27    2000    1725
28    1600    1523
29    2000    1705
30    2100    1605
31    2000    1746
32    1600    1235
33    1600    1390
34    1600    1405
35    2500    1395

In [12]:
y = df.CO2
y

0      99
1      95
2      95
3      90
4     105
5     105
6      90
7      92
8      98
9      99
10     99
11    101
12     99
13     94
14     97
15     97
16     99
17    104
18    104
19    105
20     94
21     99
22     99
23     99
24     99
25    102
26    104
27    114
28    109
29    114
30    115
31    117
32    104
33    108
34    109
35    120
Name: CO2, dtype: int64

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
model = LinearRegression()

In [15]:
model.fit(x,y)

LinearRegression()

In [16]:
coef = model.coef_
coef

array([0.00780526, 0.00755095])

In [17]:
intercept = model.intercept_
intercept

79.6947192911594

In [18]:
model.predict([[1200, 700]])

array([94.34669141])

In [19]:
y_pred = coef[0]*1200 +coef[1]*700 + intercept
y_pred

94.34669141366643

In [20]:
model.score(x, y)

0.37655640436199833

In [22]:
df1 = pd.read_csv("scale.csv")
df1.head()

Car       Model  Volume  Weight  CO2
0      Toyoty        Aygo     1.0     790   99
1  Mitsubishi  Space Star     1.2    1160   95
2       Skoda      Citigo     1.0     929   95
3        Fiat         500     0.9     865   90
4        Mini      Cooper     1.5    1140  105

In [23]:
df.head(2)

Car       Model  Volume  Weight  CO2
0      Toyoty        Aygo    1000     790   99
1  Mitsubishi  Space Star    1200    1160   95

In [24]:
df1.head(2)

Car       Model  Volume  Weight  CO2
0      Toyoty        Aygo     1.0     790   99
1  Mitsubishi  Space Star     1.2    1160   95

In [25]:
df1.describe()

Volume       Weight         CO2
count  36.000000    36.000000   36.000000
mean    1.611111  1292.277778  102.027778
std     0.388975   242.123889    7.454571
min     0.900000   790.000000   90.000000
25%     1.475000  1117.250000   97.750000
50%     1.600000  1329.000000   99.000000
75%     2.000000  1418.250000  105.000000
max     2.500000  1746.000000  120.000000

In [26]:
from sklearn.preprocessing import MinMaxScaler

In [27]:
scaler = MinMaxScaler()

In [28]:
scaled_x = scaler.fit_transform(x)
scaled_x

array([[0.0625    , 0.        ],
       [0.1875    , 0.38702929],
       [0.0625    , 0.14539749],
       [0.        , 0.07845188],
       [0.375     , 0.36610879],
       [0.0625    , 0.14539749],
       [0.3125    , 0.33368201],
       [0.375     , 0.60146444],
       [0.375     , 0.33682008],
       [0.4375    , 0.37656904],
       [0.125     , 0.19874477],
       [0.25      , 0.20920502],
       [0.0625    , 0.33682008],
       [0.4375    , 0.4832636 ],
       [0.4375    , 0.56066946],
       [0.4375    , 0.56485356],
       [0.4375    , 0.60146444],
       [0.8125    , 0.5125523 ],
       [0.4375    , 0.34414226],
       [0.6875    , 0.56276151],
       [0.4375    , 0.83054393],
       [0.6875    , 0.66736402],
       [0.75      , 0.60146444],
       [0.4375    , 0.65376569],
       [0.6875    , 0.65376569],
       [0.375     , 0.70606695],
       [0.6875    , 0.73221757],
       [0.6875    , 0.97803347],
       [0.4375    , 0.7667364 ],
       [0.6875    , 0.95711297],
       [0.

In [29]:
model.fit(scaled_x, y)

LinearRegression()

In [30]:
model.score(scaled_x, y)

0.3765564043619988

In [31]:
from sklearn.preprocessing import StandardScaler

In [32]:
scale = StandardScaler()

In [33]:
scale.fit_transform(x)

array([[-1.59336644, -2.10389253],
       [-1.07190106, -0.55407235],
       [-1.59336644, -1.52166278],
       [-1.85409913, -1.78973979],
       [-0.28970299, -0.63784641],
       [-1.59336644, -1.52166278],
       [-0.55043568, -0.76769621],
       [-0.28970299,  0.3046118 ],
       [-0.28970299, -0.7551301 ],
       [-0.0289703 , -0.59595938],
       [-1.33263375, -1.30803892],
       [-0.81116837, -1.26615189],
       [-1.59336644, -0.7551301 ],
       [-0.0289703 , -0.16871166],
       [-0.0289703 ,  0.14125238],
       [-0.0289703 ,  0.15800719],
       [-0.0289703 ,  0.3046118 ],
       [ 1.53542584, -0.05142797],
       [-0.0289703 , -0.72580918],
       [ 1.01396046,  0.14962979],
       [-0.0289703 ,  1.2219378 ],
       [ 1.01396046,  0.5685001 ],
       [ 1.27469315,  0.3046118 ],
       [-0.0289703 ,  0.51404696],
       [ 1.01396046,  0.51404696],
       [-0.28970299,  0.72348212],
       [ 1.01396046,  0.8281997 ],
       [ 1.01396046,  1.81254495],
       [-0.0289703 ,